steps:

- id: docker-build-push-service
  waitFor: ['-']
  name: gcr.io/cloud-builders/docker
  entrypoint: bash
  args:
  - -c
  - | 
    docker build -t gcr.io/$PROJECT_ID/${_SERVICE} . &&
    docker push gcr.io/$PROJECT_ID/${_SERVICE}

- id: gcloud-run-deploy-service
  waitFor: ['docker-build-push-service']
  name: gcr.io/google.com/cloudsdktool/cloud-sdk
  entrypoint: bash
  args: 
  - -c
  - | 
    gcloud run deploy ${_SERVICE} \
      --project $PROJECT_ID \
      --image gcr.io/$PROJECT_ID/${_SERVICE} \
      --cpu 2 \
      --memory 1Gi \
      --timeout 5m \
      --region ${_REGION} \
      --platform managed \
      --no-cpu-throttling \
      --concurrency 250 \
      --min-instances 0 \
      --max-instances 3 \
      --no-allow-unauthenticated

substitutions:
  _SERVICE: myva
  _REGION: us-central1
